# Generated by Django 3.1.7 on 2021-03-30 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.IntegerField()),
                ('operator', models.CharField(max_length=100)),
                ('manufacturedYear', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='when are we doing maintenance')),
                ('job', models.CharField(choices=[('S', 'Schedualed'), ('U', 'Unschedualed')], default='S', max_length=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine')),
            ],
        ),
    ]
